# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         cPanel-SyncUtil
version:      v0.0.3
version_from: lib/cPanel/SyncUtil.pm
installdirs:  site
requires:
    Archive::Tar:                  0
    Digest::MD5::File:             0
    File::Find:                    0
    File::Slurp:                   0
    Getopt::Std:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
