--- #YAML:1.0
name:                cPanel-SyncUtil
version:             0.4
abstract:            Perl extension for creating utilities that work with cpanelsync aware directories
license:             ~
author:              
    - Daniel Muey <http://drmuey.com/cpan_contact.pl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Archive::Tar:                  0
    Digest::MD5::File:             0
    File::Find:                    0
    File::Slurp:                   0
    Getopt::Std:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
